name: Quality Assurance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Cache mvn dependencies
        uses: actions/cache@v2.1.6
        env:
          cache-name: mvn-deps
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ env.cache-name }}-
      - name: Test with Maven
        run: mvn -B compile test --file pom.xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: d981a3fa-a6e8-44db-bedf-725698536732
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
